// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://grlsdxwwdyqibygdbatc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdybHNkeHd3ZHlxaWJ5Z2RiYXRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNzI1MTYsImV4cCI6MjA2NzY0ODUxNn0.dmm5OzF7nl0qcZ5Wj2CzvujYuBVgq1oCE5rGMElEJYs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  db: {
    schema: 'public'
  },
  global: {
    headers: {
      'X-Client-Info': 'lovable-app'
    }
  }
});